### PR TITLE
Add announcement of sunseting kafka from Finatra core library

### PR DESCRIPTION
**Pull request by songzhe6**
**Preview**

image

### CODE REVIEW

**Review by mosesn — APPROVED** [review]
this looks good to me.  let's get at least one more set of eyes on it though.

**Review by vkostyukov — APPROVED** [review]
LGTM as well

**Comment by songzhe6** [comment]
Hi @vkostyukov , thanks for the review! Could you please grant me the write access towards this repo? So I can merge this PR into the source. Thanks!

**Comment by vkostyukov** [comment]
I will just merge it for you.

**Pull request merged**
